import { createClient } from '@/lib/supabase/server'
import { createRequest, reviewRequest } from './actions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export default async function RequestsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null
  const { data: profile } = await supabase.from('profiles').select('role,mentor_id').eq('id', user.id).single()
  const { data: requests } = await supabase.from('leave_requests').select('id,type,reason,start_date,end_date,status,intern_id,profiles!leave_requests_intern_id_fkey(full_name)').order('created_at', { ascending: false })
  const { data: mentors } = await supabase.from('profiles').select('id,full_name').eq('role', 'mentor')
  const isReviewer = profile?.role === 'admin' || profile?.role === 'mentor'

  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-amber-600">Leave & WFH</p><h1 className="text-2xl font-semibold tracking-tight">Đơn nghỉ phép</h1><p className="mt-1 text-sm text-slate-500">Gửi yêu cầu và theo dõi trạng thái phê duyệt.</p></div>{!isReviewer && <form action={createRequest} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2"><select name="type" className="h-9 rounded-md border border-slate-200 bg-transparent px-3 text-sm"><option value="leave">Xin nghỉ phép</option><option value="wfh">Làm việc tại nhà</option></select><select name="mentor_id" defaultValue={profile?.mentor_id ?? ''} required className="h-9 rounded-md border border-slate-200 bg-transparent px-3 text-sm"><option value="">Chọn mentor</option>{mentors?.map((mentor) => <option key={mentor.id} value={mentor.id}>{mentor.full_name}</option>)}</select><Input name="start_date" type="date" required /><Input name="end_date" type="date" required /><textarea name="reason" required placeholder="Lý do" className="min-h-24 rounded-md border border-slate-200 bg-transparent p-3 text-sm sm:col-span-2" /><Button type="submit" className="sm:col-span-2">Gửi đơn</Button></form>}<section className="space-y-3">{requests?.map((request) => <article key={request.id} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h2 className="font-medium">{request.type === 'leave' ? 'Nghỉ phép' : 'Làm việc tại nhà'}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{request.status}</span></div><p className="mt-1 text-sm text-slate-500">{request.start_date} đến {request.end_date} · {request.profiles?.[0]?.full_name ?? 'Bạn'}</p><p className="mt-3 text-sm">{request.reason}</p></div>{isReviewer && request.status === 'pending' && <div className="flex gap-2"><form action={reviewRequest}><input type="hidden" name="request_id" value={request.id} /><input type="hidden" name="status" value="approved" /><Button size="sm" type="submit">Duyệt</Button></form><form action={reviewRequest}><input type="hidden" name="request_id" value={request.id} /><input type="hidden" name="status" value="rejected" /><Button size="sm" variant="outline" type="submit">Từ chối</Button></form></div>}</div></article>)}</section></div>
}