import { createClient } from '@/lib/supabase/server'
import { createEvaluation } from './actions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export default async function EvaluationsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null
  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  const { data: interns } = await supabase.from('profiles').select('id,full_name').eq('role', 'intern')
  const { data: evaluations } = await supabase.from('evaluations').select('id,type_period,feedback,scores_json,intern_id,profiles!evaluations_intern_id_fkey(full_name)').order('created_at', { ascending: false })
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-violet-600">Performance</p><h1 className="text-2xl font-semibold tracking-tight">Đánh giá</h1><p className="mt-1 text-sm text-slate-500">Ghi nhận tiến bộ và phản hồi định kỳ.</p></div>{profile?.role !== 'intern' && <form action={createEvaluation} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2"><select name="intern_id" required className="h-9 rounded-md border border-slate-200 bg-transparent px-3 text-sm"><option value="">Chọn thực tập sinh</option>{interns?.map((intern) => <option key={intern.id} value={intern.id}>{intern.full_name}</option>)}</select><select name="type_period" className="h-9 rounded-md border border-slate-200 bg-transparent px-3 text-sm"><option value="midterm">Giữa kỳ</option><option value="final">Cuối kỳ</option></select>{['technical', 'teamwork', 'discipline'].map((field) => <Input key={field} name={field} type="number" min="0" max="10" step="0.5" placeholder={`${field} (0-10)`} required />)}<textarea name="feedback" placeholder="Phản hồi" className="min-h-24 rounded-md border border-slate-200 bg-transparent p-3 text-sm sm:col-span-2" /><Button type="submit" className="sm:col-span-2">Lưu đánh giá</Button></form>}<section className="grid gap-4 md:grid-cols-2">{evaluations?.map((evaluation) => <article key={evaluation.id} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between"><h2 className="font-medium">{evaluation.profiles?.[0]?.full_name ?? 'Thực tập sinh'}</h2><span className="text-xs uppercase text-slate-500">{evaluation.type_period}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-sm">{Object.entries(evaluation.scores_json ?? {}).map(([key, value]) => <div key={key} className="rounded-lg bg-slate-50 p-2 dark:bg-slate-800"><p className="text-xs text-slate-500">{key}</p><p className="mt-1 font-semibold">{String(value)}/10</p></div>)}</div>{evaluation.feedback && <p className="mt-4 text-sm text-slate-600 dark:text-slate-300">{evaluation.feedback}</p>}</article>)}</section></div>
}